apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-a
  namespace: team-a
  labels:
    app: web
    team: a
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-a
  template:
    metadata:
      labels:
        app: web-a
        team: a
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-b
  namespace: team-b
  labels:
    app: api
    team: b
    env: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-b
  template:
    metadata:
      labels:
        app: api-b
        team: b
        env: stage
    spec:
      containers:
      - name: api
        image: ghcr.io/stefanprodan/podinfo:6.7.1
        ports:
        - containerPort: 9898
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-c
  namespace: team-c
  labels:
    app: batch
    team: c
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-c
  template:
    metadata:
      labels:
        app: batch-c
        team: c
        env: prod
    spec:
      containers:
      - name: worker
        image: busybox:1.36
        command: ["sh","-c","while true; do echo hello; sleep 5; done"]
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
