apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: ha-lab
  labels:
    app: tester
spec:
  restartPolicy: Never
  containers:
  - name: tester
    image: curlimages/curl:8.10.1
    command: ["sh","-c"]
    args:
      - |
        while true; do
          code=$(curl -s -o /dev/null -w "%{http_code}" http://web/healthz);
          echo "$(date) http_code=$code";
          sleep 1;
        done
