apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: whoami-pod-kill-one
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: whoami
