apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: whoami-cpu-stress
  namespace: chaos-mesh
spec:
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: whoami
  stressors:
    cpu:
      workers: 1
      load: 80
